### PR TITLE
Status page

### PR DESCRIPTION
**Pull request by toretefre**
Testing required and some small checks needed before ready to merge, remaining tasks are listed in issue #33 

Before I opened this Pull Request, I have:

- [ ] written 📝 code documentation where it made sense
- [ ] written tests 🔬, where it was necessary
- [ ] updated the `CHANGELOG.md` file 📝
- [ ] referenced all the issues in commits related to this PR

according to my best knowledge.

### CODE REVIEW

**Comment by Mortefal** [comment]
Needs test before it can be merged!

**Comment by toretefre** [comment]
The first two words of this *draft* PR are literally "testing required".

And yes, I'm working on it

**Comment by balazsorban44** [comment]
Shouldn't we agree on the last meeting to use the Trip view's already bulit-in "En route"  view and just expand that? 🤔

**Comment by toretefre** [comment]
> Shouldn't we agree on the last meeting to use the Trip view's already bulit-in "En route" view and just expand that? 🤔

Yes, we did. However, this PR was made prior to the meeting :)

**Pull request closed without merging**
