### PR TITLE
new logo/app name

### LINKED ISSUE #59: 🤯 Change/add logo
## Description

Add change logo to (original logo on Slack#general):

- [x] `README.md`
- [x] `assets`
- [x] `src/components/Landing/index.js`

### PR DESCRIPTION
**Pull request by PetterRein**
Before I opened this Pull Request, I have:

- [x] written 📝 code documentation where it made sense
- [x] written tests 🔬, where it was necessary
- [x] updated the `CHANGELOG.md` file 📝
- [x] referenced all the issues in commits related to this PR. closes #59 

according to my best knowledge.

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Please check the following:
- typo in `CHANGELOG.md`  (Line 10)

- could you add some screenshots of the result on different devices/screens (desktop landing, mobile splash screens, app drawers etc.) to this PR as a comment (no need to upload them to the repo itself) just for reference, and for easier review?

- use `%REACT_APP_TITLE%` environment variable in `public/index.html`, instead of static "eCatch Kyst Pilot". Though, I would argue if name/title changes are necessary at all. Did we get a request from the customer to do so? @ecatch-kyst/frontend anyone comment on this? Should we change the title from **eCatch Kyst** to **eCatch Kyst Pilot** to match the new logo? Should we ask the customer?

- Getting this in Lighthouse [report](https://www.webpagetest.org/lighthouse.php?test=190228_B3_f2237a194534eb7ade60e25628bf1e55):

[image](https://www.webpagetest.org/lighthouse.php?test=190228_B3_f2237a194534eb7ade60e25628bf1e55)

- also in the Lighthouse [report](https://www.webpagetest.org/lighthouse.php?test=190228_B3_f2237a194534eb7ade60e25628bf1e55), it looks like we went under our threshold on accessibility. Could you check this out too?

**Comment by PetterRein** [comment]
I'am checking the lighthouse
2 issues of 1 is a typo. 
Background is because I wrote 8 f's not 6 f's

But cannot fix: 
The page does not contain a heading, skip link, or landmark region
Adding ways to bypass repetitive content lets keyboard users navigate the page more efficiently. 

Failing Elements

html lang="en">

**Comment by toretefre** [comment]
> The page does not contain a heading, skip link, or landmark region

Looks like accessibility may be improved by introducing region landmarks or semantic HTML. However, i'm not sure whether this is within the scope of this PR?
Check out [https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html) for reference!

> Adding ways to bypass repetitive content lets keyboard users navigate the page more efficiently.

I don't think this is relevant for our users, as our application mainly is being used on touch devices.
If the accessibility score is impossible to reach without skip buttons, we may want to reduce our threshold score.

**Comment by PetterRein** [comment]
> > The page does not contain a heading, skip link, or landmark region
> 
> Looks like accessibility may be improved by introducing region landmarks or semantic HTML. However, i'm not sure whether this is within the scope of this PR?
> Check out https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html for reference!
> 
> > Adding ways to bypass repetitive content lets keyboard users navigate the page more efficiently.
> 
> I don't think this is relevant for our users, as our application mainly is being used on touch devices.
> If the accessibility score is impossible to reach without skip buttons, we may want to reduce our threshold score.

@balazsorban44 @toretefre 

Figured out the reason for our lower Accessibility is because we now have a picture at Landing not a H4.

Look at Index.js in Landing Line 44. Do you know a fix Balazs?

**Review by balazsorban44 — APPROVED** [review]

**Pull request merged**
